### ISSUE TITLE
Missing entrypoint

### ISSUE THREAD

**Issue by ocefpaf** [OpenDataScienceLab/skdata#30]
One [`entrypoint`](https://github.com/OpenDataScienceLab/skdata/blob/master/setup.py#L41) is listed in `setup.py` but it does not exist. This is a blocker to package `scikit-data` with packager managers that tests everything before creating the binary.  Note that `pip` does not test the `entrypoint`, but if you try to call it later you'll get:

```
> skdata --help
Traceback (most recent call last):
  File "/home/filipe/.virtualenvs/update_conda/bin/skdata", line 7, in <module>
    from skdata.cli import main
ImportError: No module named cli
```

**Comment by xmnlab** [comment]
@ocefpaf can you see if is it ok now?

**Comment by ocefpaf** [comment]
LGTM. We can follow up in the package PR later.
